= Chen Qunming - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Centralised Human Resource System (CHRS)

---

== Overview

Centralised Human Resource System (CHRS) is an application for managing employees within the company.
The application is created to assist the Human Resource Department of the company to better manage the employees' information.
CHRS is capable of checking work schedule, creating recruitment posts, checking of expenses claims and storage of various information of each employee such as salary, department, position, etc.

== Summary of contributions

* *Project Management*:
** Assists in approving, reviewing and merging pull requests.

* *Major enhancement*: added `addRecruitmentPostCommand`, `deleteRecruitmentPostCommand`, `clearRecruitmentPostCommand`
                       `editRecruitmentPostCommand`, `selectRecruitmentPostCommand`
** What it does: Allow users to manage recruitment posts for the company.
** Justification: This feature improves the product significantly because managing recruitment is one of the main responsibilities for HR admin.
** Highlights: This enhancement provides an integrated function for HR admin to manage internal recruitment posts easily before publish to the public.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=ryanchen2018&sort=displayName&since=2018-09-12&until=2018-11-04&timeframe=day&reverse=false&repoSort=true[Reposense Dashboard]}_

* *Other contributions*:

** Test cases:
*** Wrote additional tests for existing features to increase coverage from 70.2% to 80.4%(https://github.com/CS2113-AY1819S1-T16-4/main/pull/229[#229]),
82.3% to 84.9%(https://github.com/CS2113-AY1819S1-T16-4/main/pull/239[#239]),
84.9% to 88.7%(https://github.com/CS2113-AY1819S1-T16-4/main/pull/243[#243])

** Documentation:
*** Update developer guide for recruitment feature(https://github.com/CS2113-AY1819S1-T16-4/main/pull/101[#101],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/107[#107],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/108[#108],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/259[#259],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/260[#260])

*** Update user guide for recruitment feature(https://github.com/CS2113-AY1819S1-T16-4/main/pull/108[#108],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/125[#125],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/147[#147],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/149[#149],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/151[#151],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/155[#155],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/157[#157],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/160[#160],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/175[#175],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/179[#179],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/239[#239],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/259[#259])

** Community:
*** PRs reviewed (with non-trivial review comments): (
https://github.com/CS2113-AY1819S1-T16-4/main/pull/74[#74],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/75[#75],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/76[#76],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/95[#95],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/97[#97],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/112[#112],
https://github.com/CS2113-AY1819S1-T16-4/main/pull/120[#120])
*** Reported bugs and suggestions for other teams in the class (
https://github.com/CS2113-AY1819S1-W13-2/main/issues/83[#83],
https://github.com/CS2113-AY1819S1-W13-2/main/issues/85[#85],
https://github.com/CS2113-AY1819S1-W13-2/main/issues/91[#91],
https://github.com/CS2113-AY1819S1-W13-2/main/issues/95[#95],
https://github.com/CS2113-AY1819S1-W13-2/main/issues/99[#99],
https://github.com/CS2113-AY1819S1-W13-2/main/issues/103[#103])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addRecruitmentPostCommand]

include::../UserGuide.adoc[tag=editRecruitmentPostCommand]

include::../UserGuide.adoc[tag=selectRecruitmentPostCommand]

include::../UserGuide.adoc[tag=deleteRecruitmentPostCommand]

include::../UserGuide.adoc[tag=clearRecruitmentPostCommand]

include::../UserGuide.adoc[tag=recruitment2.0Feature]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=RecruitmentPost]


